export type Product = { id: string; slug: string; name: string; category: string; price: number; oldPrice?: number; rating: number; stock: number; image: string; description: string; features: string[]; featured?: boolean };
export const products: Product[] = [
  { id:"p1", slug:"aero-pro-charger", name:"Aero Pro Charger", category:"Electronics", price:1299, oldPrice:1699, rating:4.9, stock:18, image:"https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=85", description:"A compact 65W GaN charger engineered for fast, cooler power.", features:["65W USB-C PD","Two-device charging","Travel-ready GaN design"], featured:true },
  { id:"p2", slug:"halo-desk-lamp", name:"Halo Desk Lamp", category:"Home", price:2499, rating:4.8, stock:11, image:"https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&w=900&q=85", description:"Atmospheric, adjustable light for focused work and slow evenings.", features:["Touch dimming","Warm-to-cool tone","Minimal aluminium body"], featured:true },
  { id:"p3", slug:"form-steel-bottle", name:"Form Steel Bottle", category:"Fitness", price:899, oldPrice:1099, rating:4.7, stock:36, image:"https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=85", description:"A double-wall everyday bottle that holds temperature beautifully.", features:["750ml","24-hour cold","Leakproof lid"] },
  { id:"p4", slug:"ritual-skin-set", name:"Ritual Skin Set", category:"Beauty", price:1899, rating:4.8, stock:9, image:"https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=85", description:"A considered three-step routine for a polished daily reset.", features:["Clean ingredients","Three-piece set","Gift-ready box"] },
  { id:"p5", slug:"arc-wireless-stand", name:"Arc Wireless Stand", category:"Accessories", price:1599, rating:4.6, stock:22, image:"https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=85", description:"A sculptural charging stand for your bedside or studio.", features:["15W Qi","Portrait / landscape","Non-slip base"] },
  { id:"p6", slug:"studio-planner", name:"Studio Planner", category:"Stationery", price:649, rating:4.9, stock:42, image:"https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=900&q=85", description:"Undated planning pages for clear thinking and calm momentum.", features:["Undated format","100gsm paper","Monthly review pages"] }
];
export const websites = [
  { title:"Velora Salon", category:"Salon", stack:"Next.js · Stripe · CMS", image:"https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=1200&q=85", text:"A refined booking experience built for repeat appointments." },
  { title:"Cinder & Co.", category:"Restaurant", stack:"Next.js · Reservations · SEO", image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85", text:"A narrative-led hospitality site with a highly usable menu." },
  { title:"Altitude Training", category:"Gym", stack:"React · Motion · Analytics", image:"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=85", text:"A conversion-focused fitness brand and class discovery flow." },
  { title:"Noru Cycles", category:"E-Commerce", stack:"Next.js · Commerce · Shopify", image:"https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=85", text:"A cinematic ecommerce storefront for contemporary cycling." }
];
export const categories = ["Kitchen","Electronics","Fitness","Beauty","Accessories","Lifestyle","Home","Stationery"];
